/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Andre
 */
public class FormProdutos extends javax.swing.JInternalFrame {

    private final ProdutoController Controller;

    //construtor

    public FormProdutos() {
        initComponents();
        this.Controller = new ProdutoController(this);
        this.Controller.CarregaTabelaProduto();
        this.Controller.atualizarFornecedor();
        this.Controller.ObterFornecedor();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoProCod = new javax.swing.JTextField();
        CampoProNome = new javax.swing.JTextField();
        CampoProDesc = new javax.swing.JTextField();
        CampoProUN = new javax.swing.JTextField();
        CampoProVal = new javax.swing.JTextField();
        jComboBoxProFor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedCampoProCNPJ = new javax.swing.JFormattedTextField();
        CampoProCodFor = new javax.swing.JTextField();
        TabelaProdutos = new javax.swing.JScrollPane();
        javax.swing.JTable TabelaProdutosT = new javax.swing.JTable();
        bntProCad = new javax.swing.JButton();
        bnbProAtu = new javax.swing.JButton();
        bntProLim = new javax.swing.JButton();
        bntProCan = new javax.swing.JButton();
        bntProEdi = new javax.swing.JButton();
        bntProExc = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1240, 550));
        setPreferredSize(new java.awt.Dimension(1240, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Controle de produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados cadastrais"));

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Descrição:");

        jLabel5.setText("Unidade:");

        jLabel6.setText("Valor Unitario:");

        CampoProCod.setEditable(false);

        jComboBoxProFor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProForActionPerformed(evt);
            }
        });

        jLabel7.setText("Fornecedor:");

        jLabel8.setText("Codigo Fornecedor:");

        jLabel9.setText("Cnpj:");

        jFormattedCampoProCNPJ.setEditable(false);
        try {
            jFormattedCampoProCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCampoProCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedCampoProCNPJActionPerformed(evt);
            }
        });

        CampoProCodFor.setEditable(false);
        CampoProCodFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoProCodForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CampoProCod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoProUN, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoProNome, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                        .addComponent(CampoProDesc)))
                                .addGap(0, 62, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(CampoProVal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedCampoProCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxProFor, 0, 155, Short.MAX_VALUE)
                        .addComponent(CampoProCodFor)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CampoProCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoProNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)
                        .addComponent(CampoProDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CampoProCodFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoProUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedCampoProCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoProVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(56, 56, 56))
        );

        TabelaProdutosT.setAutoCreateRowSorter(true);
        TabelaProdutosT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Valor Unitario", "Codigo Fornecedor"
            }
        ));
        TabelaProdutos.setViewportView(TabelaProdutosT);

        bntProCad.setText("Cadastrar");
        bntProCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProCadActionPerformed(evt);
            }
        });

        bnbProAtu.setText("Atualizar");
        bnbProAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbProAtuActionPerformed(evt);
            }
        });

        bntProLim.setText("Limpar");
        bntProLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProLimActionPerformed(evt);
            }
        });

        bntProCan.setText("Cancelar");
        bntProCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProCanActionPerformed(evt);
            }
        });

        bntProEdi.setText("Editar");
        bntProEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProEdiActionPerformed(evt);
            }
        });

        bntProExc.setText("Excluir");
        bntProExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProExcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TabelaProdutos)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bntProCad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnbProAtu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntProLim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntProCan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntProEdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntProExc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(381, 381, 381))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntProCad)
                        .addGap(33, 33, 33)
                        .addComponent(bnbProAtu)
                        .addGap(30, 30, 30)
                        .addComponent(bntProLim)
                        .addGap(36, 36, 36)
                        .addComponent(bntProCan)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabelaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(bntProEdi)
                        .addGap(18, 18, 18)
                        .addComponent(bntProExc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setBounds(0, 0, 1240, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedCampoProCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedCampoProCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedCampoProCNPJActionPerformed

    private void CampoProCodForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoProCodForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoProCodForActionPerformed

    private void jComboBoxProForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProForActionPerformed
        this.Controller.ObterFornecedor();
    }//GEN-LAST:event_jComboBoxProForActionPerformed

    private void bntProCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProCadActionPerformed
        this.Controller.cadastrarProduto();
    }//GEN-LAST:event_bntProCadActionPerformed

    private void bnbProAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbProAtuActionPerformed
        this.Controller.AtualizarProduto();
    }//GEN-LAST:event_bnbProAtuActionPerformed

    private void bntProLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProLimActionPerformed
        this.Controller.limparProdutos();
    }//GEN-LAST:event_bntProLimActionPerformed

    private void bntProCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProCanActionPerformed
        this.Controller.CancelarProduto();
    }//GEN-LAST:event_bntProCanActionPerformed

    private void bntProEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProEdiActionPerformed
        this.Controller.EditarProduto();
    }//GEN-LAST:event_bntProEdiActionPerformed

    private void bntProExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProExcActionPerformed
        this.Controller.ExcluirProduto();
    }//GEN-LAST:event_bntProExcActionPerformed

    private javax.swing.JTable TabelaProdutosT ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoProCod;
    private javax.swing.JTextField CampoProCodFor;
    private javax.swing.JTextField CampoProDesc;
    private javax.swing.JTextField CampoProNome;
    private javax.swing.JTextField CampoProUN;
    private javax.swing.JTextField CampoProVal;
    private javax.swing.JScrollPane TabelaProdutos;
    private javax.swing.JButton bnbProAtu;
    private javax.swing.JButton bntProCad;
    private javax.swing.JButton bntProCan;
    private javax.swing.JButton bntProEdi;
    private javax.swing.JButton bntProExc;
    private javax.swing.JButton bntProLim;
    private javax.swing.JComboBox jComboBoxProFor;
    private javax.swing.JFormattedTextField jFormattedCampoProCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelaProdutosT() {
        return TabelaProdutosT;
    }

    public void setTabelaProdutosT(JTable TabelaProdutosT) {
        this.TabelaProdutosT = TabelaProdutosT;
    }

    
    
    public JFormattedTextField getjFormattedCampoProCNPJ() {
        return jFormattedCampoProCNPJ;
    }

    public void setjFormattedCampoProCNPJ(JFormattedTextField jFormattedCampoProCNPJ) {
        this.jFormattedCampoProCNPJ = jFormattedCampoProCNPJ;
    }

    public JTextField getCampoProCod() {
        return CampoProCod;
    }

    public void setCampoProCod(JTextField CampoProCod) {
        this.CampoProCod = CampoProCod;
    }

    public JTextField getCampoProCodFor() {
        return CampoProCodFor;
    }

    public void setCampoProCodFor(JTextField CampoProCodFor) {
        this.CampoProCodFor = CampoProCodFor;
    }

    public JTextField getCampoProDesc() {
        return CampoProDesc;
    }

    public void setCampoProDesc(JTextField CampoProDesc) {
        this.CampoProDesc = CampoProDesc;
    }

    public JTextField getCampoProNome() {
        return CampoProNome;
    }

    public void setCampoProNome(JTextField CampoProNome) {
        this.CampoProNome = CampoProNome;
    }

    public JTextField getCampoProUN() {
        return CampoProUN;
    }

    public void setCampoProUN(JTextField CampoProUN) {
        this.CampoProUN = CampoProUN;
    }

    public JTextField getCampoProVal() {
        return CampoProVal;
    }

    public void setCampoProVal(JTextField CampoProVal) {
        this.CampoProVal = CampoProVal;
    }

    public JScrollPane getTabelaProdutos() {
        return TabelaProdutos;
    }

    public void setTabelaProdutos(JScrollPane TabelaProdutos) {
        this.TabelaProdutos = TabelaProdutos;
    }

    public JButton getBnbProAtu() {
        return bnbProAtu;
    }

    public void setBnbProAtu(JButton bnbProAtu) {
        this.bnbProAtu = bnbProAtu;
    }

    public JButton getBntProCad() {
        return bntProCad;
    }

    public void setBntProCad(JButton bntProCad) {
        this.bntProCad = bntProCad;
    }

    public JButton getBntProCan() {
        return bntProCan;
    }

    public void setBntProCan(JButton bntProCan) {
        this.bntProCan = bntProCan;
    }

    public JButton getBntProEdi() {
        return bntProEdi;
    }

    public void setBntProEdi(JButton bntProEdi) {
        this.bntProEdi = bntProEdi;
    }

    public JButton getBntProExc() {
        return bntProExc;
    }

    public void setBntProExc(JButton bntProExc) {
        this.bntProExc = bntProExc;
    }

    public JButton getBntProLim() {
        return bntProLim;
    }

    public void setBntProLim(JButton bntProLim) {
        this.bntProLim = bntProLim;
    }

    public JComboBox getjComboBoxProFor() {
        return jComboBoxProFor;
    }

    public void setjComboBoxProFor(JComboBox jComboBoxProFor) {
        this.jComboBoxProFor = jComboBoxProFor;
    }

}
