/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FornecedorController;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Andre
 */
public class FormFornecedor extends javax.swing.JInternalFrame {

    private final FornecedorController controller;
     // contrutor
    public FormFornecedor() {
        initComponents();
        this.controller = new FornecedorController(this);
        this.controller.CarregaTabelaFornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoForCod = new javax.swing.JTextField();
        CampoForNome = new javax.swing.JTextField();
        CampoForCNPJ = new javax.swing.JFormattedTextField();
        campoForTel = new javax.swing.JFormattedTextField();
        CampoForFax = new javax.swing.JTextField();
        CampoForEma = new javax.swing.JTextField();
        CampoForSit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedor = new javax.swing.JTable();
        bntForCad = new javax.swing.JButton();
        bntForAtu = new javax.swing.JButton();
        bntForLim = new javax.swing.JButton();
        bntForCan = new javax.swing.JButton();
        bntForEditar = new javax.swing.JButton();
        bntForExc = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Fornecedor");
        setPreferredSize(new java.awt.Dimension(1240, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Cadastrais"));

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("CNPJ:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Fax:");

        jLabel6.setText("Email:");

        jLabel7.setText("Site:");

        CampoForCod.setEnabled(false);

        try {
            CampoForCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoForTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CampoForCod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoForNome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoForFax))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoForEma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoForSit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoForTel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoForCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CampoForCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CampoForNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(CampoForCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(campoForTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoForFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CampoForEma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CampoForSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        TabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "CNPJ", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(TabelaFornecedor);

        bntForCad.setText("Cadastrar");
        bntForCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForCadActionPerformed(evt);
            }
        });

        bntForAtu.setText("Atualizar");
        bntForAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForAtuActionPerformed(evt);
            }
        });

        bntForLim.setText("Limpar");
        bntForLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForLimActionPerformed(evt);
            }
        });

        bntForCan.setText("Cancelar");
        bntForCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForCanActionPerformed(evt);
            }
        });

        bntForEditar.setText("Editar");
        bntForEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForEditarActionPerformed(evt);
            }
        });

        bntForExc.setText("Excluir");
        bntForExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntForExcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntForCad)
                            .addComponent(bntForAtu)
                            .addComponent(bntForLim)
                            .addComponent(bntForCan)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntForEditar)
                            .addComponent(bntForExc))))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bntForCad)
                        .addGap(18, 18, 18)
                        .addComponent(bntForAtu)
                        .addGap(18, 18, 18)
                        .addComponent(bntForLim)
                        .addGap(18, 18, 18)
                        .addComponent(bntForCan)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntForEditar)
                        .addGap(37, 37, 37)
                        .addComponent(bntForExc)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1240, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void bntForEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForEditarActionPerformed
        // TODO add your handling code here:
        this.controller.EditarFornecedor();
    }//GEN-LAST:event_bntForEditarActionPerformed

    private void bntForAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForAtuActionPerformed
        this.controller.AtualizarFornecedor();
    }//GEN-LAST:event_bntForAtuActionPerformed

    private void bntForExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForExcActionPerformed
        this.controller.ExcluirFornecedor();
    }//GEN-LAST:event_bntForExcActionPerformed

    private void bntForCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForCadActionPerformed
        // TODO add your handling code here:
        this.controller.cadastrarFornecedor();
    }//GEN-LAST:event_bntForCadActionPerformed

    private void bntForLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForLimActionPerformed
        this.controller.limparCampos();
    }//GEN-LAST:event_bntForLimActionPerformed

    private void bntForCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntForCanActionPerformed
        this.controller.CancelarFornecedor();
    }//GEN-LAST:event_bntForCanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CampoForCNPJ;
    private javax.swing.JTextField CampoForCod;
    private javax.swing.JTextField CampoForEma;
    private javax.swing.JTextField CampoForFax;
    private javax.swing.JTextField CampoForNome;
    private javax.swing.JTextField CampoForSit;
    private javax.swing.JTable TabelaFornecedor;
    private javax.swing.JButton bntForAtu;
    private javax.swing.JButton bntForCad;
    private javax.swing.JButton bntForCan;
    private javax.swing.JButton bntForEditar;
    private javax.swing.JButton bntForExc;
    private javax.swing.JButton bntForLim;
    private javax.swing.JFormattedTextField campoForTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JFormattedTextField getCampoForCNPJ() {
        return CampoForCNPJ;
    }

    public void setCampoForCNPJ(JFormattedTextField CampoForCNPJ) {
        this.CampoForCNPJ = CampoForCNPJ;
    }

    public JTextField getCampoForCod() {
        return CampoForCod;
    }

    public void setCampoForCod(JTextField CampoForCod) {
        this.CampoForCod = CampoForCod;
    }

    public JTextField getCampoForEma() {
        return CampoForEma;
    }

    public void setCampoForEma(JTextField CampoForEma) {
        this.CampoForEma = CampoForEma;
    }

    public JTextField getCampoForFax() {
        return CampoForFax;
    }

    public void setCampoForFax(JTextField CampoForFax) {
        this.CampoForFax = CampoForFax;
    }

    public JTextField getCampoForNome() {
        return CampoForNome;
    }

    public void setCampoForNome(JTextField CampoForNome) {
        this.CampoForNome = CampoForNome;
    }

    public JTextField getCampoForSit() {
        return CampoForSit;
    }

    public void setCampoForSit(JTextField CampoForSit) {
        this.CampoForSit = CampoForSit;
    }

    public JButton getBntForAtu() {
        return bntForAtu;
    }

    public void setBntForAtu(JButton bntForAtu) {
        this.bntForAtu = bntForAtu;
    }

    public JButton getBntForCad() {
        return bntForCad;
    }

    public void setBntForCad(JButton bntForCad) {
        this.bntForCad = bntForCad;
    }

    public JButton getBntForCan() {
        return bntForCan;
    }

    public void setBntForCan(JButton bntForCan) {
        this.bntForCan = bntForCan;
    }

    public JButton getBntForEditar() {
        return bntForEditar;
    }

    public void setBntForEditar(JButton bntForEditar) {
        this.bntForEditar = bntForEditar;
    }

    public JButton getBntForExc() {
        return bntForExc;
    }

    public void setBntForExc(JButton bntForExc) {
        this.bntForExc = bntForExc;
    }

    public JButton getBntForLim() {
        return bntForLim;
    }

    public void setBntForLim(JButton bntForLim) {
        this.bntForLim = bntForLim;
    }

    public JFormattedTextField getCampoForTel() {
        return campoForTel;
    }

    public void setCampoForTel(JFormattedTextField campoForTel) {
        this.campoForTel = campoForTel;
    }

    public JTable getTabelaFornecedor() {
        return TabelaFornecedor;
    }

    public void setTabelaFornecedor(JTable TabelaFornecedor) {
        this.TabelaFornecedor = TabelaFornecedor;
    }





}
